export const ttlockEndpoint = {
	user: {
		list: "https://api.sciener.com/v3/user/list",
		register: "https://api.sciener.com/v3/user/register",
		login: "https://api.sciener.com/oauth2/token",
		resetPassword: "https://api.sciener.com/v3/user/resetPassword",
		delete: "https://api.sciener.com/v3/user/delete",
	},
	lock: {
		initialize: "https://api.sciener.com/v3/lock/initialize",
		detail: "https://euapi.ttlock.com/v3/lock/detail",
		battery: "https://api.sciener.com/v3/lock/queryElectricQuantity",
		passageMode: "https://api.sciener.com/v3/lock/getPassageModeConfig",
		list: "https://api.sciener.com/v3/lock/list",
		listPasscodes: "https://api.sciener.com/v3/lock/listKeyboardPwd",
		listUsers: "https://api.sciener.com/v3/lock/listKey",
		lock: "https://api.sciener.com/v3/lock/lock",
		unlock: "https://api.sciener.com/v3/lock/unlock",
		rename: "https://api.sciener.com/v3/lock/rename",
		updateBattery: "https://api.sciener.com/v3/lock/updateElectricQuantity",
		setAutoLock: "https://api.sciener.com/v3/lock/setAutoLockTime",
		changeAdminPasscode: "https://api.sciener.com/v3/lock/changeAdminKeyboardPwd",
		transfer: "https://api.sciener.com/v3/lock/transfer",
		updateLockData: "https://api.sciener.com/v3/lock/updateLockData",
		setHotelCardSector: "https://api.sciener.com/v3/lock/setHotelCardSector",
		delete: "https://api.sciener.com/v3/lock/delete",
		deletePasscode: "https://api.sciener.com/v3/lock/changeDeletePwd",
		deleteAllKeys: "https://api.sciener.com/v3/lock/deleteAllKey",
		configPassageMode: "https://api.sciener.com/v3/lock/configPassageMode",
		queryOpenState: "https://euapi.ttlock.com/v3/lock/queryOpenState",
		configurePassageMode: "https://euapi.ttlock.com/v3/lock/configurePassageMode",
		getPassageModeConfiguration: "https://euapi.ttlock.com/v3/lock/getPassageModeConfiguration",
		updateSetting: "https://euapi.ttlock.com/v3/lock/updateSetting",
		querySetting: "https://euapi.ttlock.com/v3/lock/querySetting",
	},
	passcode: {
		list: "https://euapi.ttlock.com/v3/lock/listKeyboardPwd",
		get: "https://euapi.ttlock.com/v3/keyboardPwd/get",
		add: "https://api.sciener.com/v3/keyboardPwd/add",
		change: "https://api.sciener.com/v3/keyboardPwd/change",
		delete: "https://api.sciener.com/v3/keyboardPwd/delete",
	},
	fingerprint: {
		list: "https://api.sciener.com/v3/fingerprint/list",
		add: "https://api.sciener.com/v3/fingerprint/add",
		delete: "https://api.sciener.com/v3/fingerprint/delete",
		clear: "https://api.sciener.com/v3/fingerprint/clear",
		changePeriod: "https://api.sciener.com/v3/fingerprint/changePeriod",
		rename: "https://api.sciener.com/v3/fingerprint/rename",
	},
	doorSensor: {
		add: "https://euapi.ttlock.com/v3/doorSensor/add",
		query: "https://euapi.ttlock.com/v3/doorSensor/query",
		delete: "https://euapi.ttlock.com/v3/doorSensor/delete",
		update: "https://euapi.ttlock.com/v3/doorSensor/update",
	},
	qrcode: {
		list: "https://api.sciener.com/v3/qrCode/list",
		add: "https://api.sciener.com/v3/qrCode/add",
		getData: "https://api.sciener.com/v3/qrCode/getData",
		delete: "https://api.sciener.com/v3/qrCode/delete",
		clear: "https://api.sciener.com/v3/qrCode/clear",
		update: "https://api.sciener.com/v3/qrCode/update",
	},
	gateway: {
		initialize: "https://api.sciener.com/v3/gateway/initialize",
		checkStatus: "https://api.sciener.com/v3/gateway/isInitSuccess",
		list: "https://api.sciener.com/v3/gateway/list",
		delete: "https://api.sciener.com/v3/gateway/delete",
		getDetails: "https://api.sciener.com/v3/gateway/detail",
		update: "https://api.sciener.com/v3/gateway/update",
		uploadDetails: "https://api.sciener.com/v3/gateway/uploadDetail",
		getUserId: "https://api.sciener.com/v3/user/getUid",
		getLockTime: "https://api.sciener.com/v3/lock/queryDate",
		getLockStatus: "https://api.sciener.com/v3/lock/queryStatus",
		listLocks: "https://api.sciener.com/v3/gateway/listLock",
		checkUpgrade: "https://api.sciener.com/v3/gateway/upgradeCheck",
		adjustTime: "https://api.sciener.com/v3/lock/updateDate",
		freezeLock: "https://api.sciener.com/v3/lock/freeze",
		unfreezeLock: "https://api.sciener.com/v3/lock/unfreeze",
		transfer: "https://api.sciener.com/v3/gateway/transfer",
		setUpgradeMode: "https://api.sciener.com/v3/gateway/setUpgradeMode",
		listByLock: "https://euapi.ttlock.com/v3/gateway/listByLock",
	},
	icCard: {
		add: "https://euapi.ttlock.com/v3/identityCard/addForReversedCardNumber",
		list: "https://euapi.ttlock.com/v3/identityCard/list",
		delete: "https://euapi.ttlock.com/v3/identityCard/delete",
		clear: "https://euapi.ttlock.com/v3/identityCard/clear",
		changePeriod: "https://euapi.ttlock.com/v3/identityCard/changePeriod",
		rename: "https://euapi.ttlock.com/v3/identityCard/rename",
	},
	ekey: {
		send: "https://api.sciener.com/v3/key/send",
		delete: "https://api.sciener.com/v3/key/delete",
		list: "https://api.sciener.com/v3/key/list",
		get: "https://api.sciener.com/v3/key/get",
		freeze: "https://api.sciener.com/v3/key/freeze",
		unfreeze: "https://api.sciener.com/v3/key/unfreeze",
		modify: "https://api.sciener.com/v3/key/update",
		changePeriod: "https://api.sciener.com/v3/key/changePeriod",
		authorize: "https://api.sciener.com/v3/key/authorize",
		unauthorize: "https://api.sciener.com/v3/key/unauthorize",
	},
	unlockRecord: {
		list: "https://api.sciener.com/v3/lockRecord/list",
		upload: "https://api.sciener.com/v3/lockRecord/upload",
		delete: "https://euapi.ttlock.com/v3/lockRecord/delete",
		clear: "https://euapi.ttlock.com/v3/lockRecord/clear",
	},
	group: {
		add: "https://api.sciener.com/v3/group/add",
		list: "https://api.sciener.com/v3/group/list",
		update: "https://api.sciener.com/v3/group/update",
		delete: "https://api.sciener.com/v3/group/delete",
		setLock: "https://api.sciener.com/v3/lock/setGroup",
	},
};
